# permissions for end users to view testowners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: testowner-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: testowner-operator
    app.kubernetes.io/part-of: testowner-operator
    app.kubernetes.io/managed-by: kustomize
  name: testowner-viewer-role
rules:
- apiGroups:
  - test.github.com
  resources:
  - testowners
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - test.github.com
  resources:
  - testowners/status
  verbs:
  - get
