# permissions for end users to edit testdependents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: testdependent-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: testowner-operator
    app.kubernetes.io/part-of: testowner-operator
    app.kubernetes.io/managed-by: kustomize
  name: testdependent-editor-role
rules:
- apiGroups:
  - test.github.com
  resources:
  - testdependents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - test.github.com
  resources:
  - testdependents/status
  verbs:
  - get
