# The following patch enables a conversion webhook for the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: testdependents.test.github.com
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          namespace: testowner-operator-system
          name: webhook-service
          path: /convert
      conversionReviewVersions:
      - v1
