apiVersion: test.github.com/v1alpha1
kind: TestDependent
metadata:
  labels:
    app.kubernetes.io/name: testdependent
    app.kubernetes.io/instance: testdependent-sample
    app.kubernetes.io/part-of: testowner-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: testowner-operator
  name: testdependent-sample
spec:
  # TODO(user): Add fields here
